export const countries = [
  { id: 1, code: 'AF', name: 'Afghanistan', phoneCode: '+93' },
  { id: 2, code: 'AL', name: 'Albania', phoneCode: '+355' },
  { id: 3, code: 'DZ', name: 'Algeria', phoneCode: '+213' },
  { id: 4, code: 'AD', name: 'Andorra', phoneCode: '+376' },
  { id: 5, code: 'AO', name: 'Angola', phoneCode: '+244' },
  { id: 6, code: 'AR', name: 'Argentina', phoneCode: '+54' },
  { id: 7, code: 'AM', name: 'Armenia', phoneCode: '+374' },
  { id: 8, code: 'AU', name: 'Australia', phoneCode: '+61' },
  { id: 9, code: 'AT', name: 'Austria', phoneCode: '+43' },
  { id: 10, code: 'AZ', name: 'Azerbaijan', phoneCode: '+994' },
  { id: 11, code: 'BH', name: 'Bahrain', phoneCode: '+973' },
  { id: 12, code: 'BD', name: 'Bangladesh', phoneCode: '+880' },
  { id: 13, code: 'BY', name: 'Belarus', phoneCode: '+375' },
  { id: 14, code: 'BE', name: 'Belgium', phoneCode: '+32' },
  { id: 15, code: 'BJ', name: 'Benin', phoneCode: '+229' },
  { id: 16, code: 'BT', name: 'Bhutan', phoneCode: '+975' },
  { id: 17, code: 'BO', name: 'Bolivia', phoneCode: '+591' },
  { id: 18, code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387' },
  { id: 19, code: 'BW', name: 'Botswana', phoneCode: '+267' },
  { id: 20, code: 'BR', name: 'Brazil', phoneCode: '+55' },
  { id: 21, code: 'BG', name: 'Bulgaria', phoneCode: '+359' },
  { id: 22, code: 'BF', name: 'Burkina Faso', phoneCode: '+226' },
  { id: 23, code: 'BI', name: 'Burundi', phoneCode: '+257' },
  { id: 24, code: 'KH', name: 'Cambodia', phoneCode: '+855' },
  { id: 25, code: 'CM', name: 'Cameroon', phoneCode: '+237' },
  { id: 26, code: 'CA', name: 'Canada', phoneCode: '+1' },
  { id: 27, code: 'CV', name: 'Cape Verde', phoneCode: '+238' },
  { id: 28, code: 'CF', name: 'Central African Republic', phoneCode: '+236' },
  { id: 29, code: 'TD', name: 'Chad', phoneCode: '+235' },
  { id: 30, code: 'CL', name: 'Chile', phoneCode: '+56' },
  { id: 31, code: 'CN', name: 'China', phoneCode: '+86' },
  { id: 32, code: 'CO', name: 'Colombia', phoneCode: '+57' },
  { id: 33, code: 'KM', name: 'Comoros', phoneCode: '+269' },
  { id: 34, code: 'CD', name: 'Congo (Kinshasa)', phoneCode: '+243' },
  { id: 35, code: 'CG', name: 'Congo (Brazzaville)', phoneCode: '+242' },
  { id: 36, code: 'CR', name: 'Costa Rica', phoneCode: '+506' },
  { id: 37, code: 'CI', name: 'Côte d\'Ivoire', phoneCode: '+225' },
  { id: 38, code: 'HR', name: 'Croatia', phoneCode: '+385' },
  { id: 39, code: 'CY', name: 'Cyprus', phoneCode: '+357' },
  { id: 40, code: 'CZ', name: 'Czech Republic', phoneCode: '+420' },
  { id: 41, code: 'DK', name: 'Denmark', phoneCode: '+45' },
  { id: 42, code: 'DJ', name: 'Djibouti', phoneCode: '+253' },
  { id: 43, code: 'DM', name: 'Dominica', phoneCode: '+1-767' },
  { id: 44, code: 'DO', name: 'Dominican Republic', phoneCode: '+1-809' },
  { id: 45, code: 'EC', name: 'Ecuador', phoneCode: '+593' },
  { id: 46, code: 'EG', name: 'Egypt', phoneCode: '+20' },
  { id: 47, code: 'SV', name: 'El Salvador', phoneCode: '+503' },
  { id: 48, code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240' },
  { id: 49, code: 'ER', name: 'Eritrea', phoneCode: '+291' },
  { id: 50, code: 'EE', name: 'Estonia', phoneCode: '+372' },
  { id: 51, code: 'ET', name: 'Ethiopia', phoneCode: '+251' },
  { id: 52, code: 'FI', name: 'Finland', phoneCode: '+358' },
  { id: 53, code: 'FR', name: 'France', phoneCode: '+33' },
  { id: 54, code: 'GA', name: 'Gabon', phoneCode: '+241' },
  { id: 55, code: 'GM', name: 'Gambia', phoneCode: '+220' },
  { id: 56, code: 'GE', name: 'Georgia', phoneCode: '+995' },
  { id: 57, code: 'DE', name: 'Germany', phoneCode: '+49' },
  { id: 58, code: 'GH', name: 'Ghana', phoneCode: '+233' },
  { id: 59, code: 'GR', name: 'Greece', phoneCode: '+30' },
  { id: 60, code: 'GT', name: 'Guatemala', phoneCode: '+502' },
  { id: 61, code: 'GN', name: 'Guinea', phoneCode: '+224' },
  { id: 62, code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245' },
  { id: 63, code: 'GY', name: 'Guyana', phoneCode: '+592' },
  { id: 64, code: 'HT', name: 'Haiti', phoneCode: '+509' },
  { id: 65, code: 'HN', name: 'Honduras', phoneCode: '+504' },
  { id: 66, code: 'HK', name: 'Hong Kong', phoneCode: '+852' },
  { id: 67, code: 'HU', name: 'Hungary', phoneCode: '+36' },
  { id: 68, code: 'IS', name: 'Iceland', phoneCode: '+354' },
  { id: 69, code: 'IN', name: 'India', phoneCode: '+91' },
  { id: 70, code: 'ID', name: 'Indonesia', phoneCode: '+62' },
  { id: 71, code: 'IR', name: 'Iran', phoneCode: '+98' },
  { id: 72, code: 'IQ', name: 'Iraq', phoneCode: '+964' },
  { id: 73, code: 'IE', name: 'Ireland', phoneCode: '+353' },
  { id: 74, code: 'IL', name: 'Israel', phoneCode: '+972' },
  { id: 75, code: 'IT', name: 'Italy', phoneCode: '+39' },
  { id: 76, code: 'JM', name: 'Jamaica', phoneCode: '+1-876' },
  { id: 77, code: 'JP', name: 'Japan', phoneCode: '+81' },
  { id: 78, code: 'JO', name: 'Jordan', phoneCode: '+962' },
  { id: 79, code: 'KZ', name: 'Kazakhstan', phoneCode: '+7' },
  { id: 80, code: 'KE', name: 'Kenya', phoneCode: '+254' },
  { id: 81, code: 'KR', name: 'South Korea', phoneCode: '+82' },
  { id: 82, code: 'KW', name: 'Kuwait', phoneCode: '+965' },
  { id: 83, code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996' },
  { id: 84, code: 'LA', name: 'Laos', phoneCode: '+856' },
  { id: 85, code: 'LV', name: 'Latvia', phoneCode: '+371' },
  { id: 86, code: 'LB', name: 'Lebanon', phoneCode: '+961' },
  { id: 87, code: 'LR', name: 'Liberia', phoneCode: '+231' },
  { id: 88, code: 'LY', name: 'Libya', phoneCode: '+218' },
  { id: 89, code: 'LT', name: 'Lithuania', phoneCode: '+370' },
  { id: 90, code: 'LU', name: 'Luxembourg', phoneCode: '+352' },
  { id: 91, code: 'MG', name: 'Madagascar', phoneCode: '+261' },
  { id: 92, code: 'MW', name: 'Malawi', phoneCode: '+265' },
  { id: 93, code: 'MY', name: 'Malaysia', phoneCode: '+60' },
  { id: 94, code: 'MV', name: 'Maldives', phoneCode: '+960' },
  { id: 95, code: 'ML', name: 'Mali', phoneCode: '+223' },
  { id: 96, code: 'MT', name: 'Malta', phoneCode: '+356' },
  { id: 97, code: 'MX', name: 'Mexico', phoneCode: '+52' },
  { id: 98, code: 'MD', name: 'Moldova', phoneCode: '+373' },
  { id: 99, code: 'MC', name: 'Monaco', phoneCode: '+377' },
  { id: 100, code: 'MN', name: 'Mongolia', phoneCode: '+976' },
  { id: 101, code: 'MA', name: 'Morocco', phoneCode: '+212' },
  { id: 102, code: 'MZ', name: 'Mozambique', phoneCode: '+258' },
  { id: 103, code: 'MM', name: 'Myanmar (Burma)', phoneCode: '+95' },
  { id: 104, code: 'NA', name: 'Namibia', phoneCode: '+264' },
  { id: 105, code: 'NP', name: 'Nepal', phoneCode: '+977' },
  { id: 106, code: 'NL', name: 'Netherlands', phoneCode: '+31' },
  { id: 107, code: 'NZ', name: 'New Zealand', phoneCode: '+64' },
  { id: 108, code: 'NI', name: 'Nicaragua', phoneCode: '+505' },
  { id: 109, code: 'NE', name: 'Niger', phoneCode: '+227' },
  { id: 110, code: 'NG', name: 'Nigeria', phoneCode: '+234' },
  { id: 111, code: 'NO', name: 'Norway', phoneCode: '+47' },
  { id: 112, code: 'OM', name: 'Oman', phoneCode: '+968' },
  { id: 113, code: 'PK', name: 'Pakistan', phoneCode: '+92' },
  { id: 114, code: 'PA', name: 'Panama', phoneCode: '+507' },
  { id: 115, code: 'PG', name: 'Papua New Guinea', phoneCode: '+675' },
  { id: 116, code: 'PY', name: 'Paraguay', phoneCode: '+595' },
  { id: 117, code: 'PE', name: 'Peru', phoneCode: '+51' },
  { id: 118, code: 'PH', name: 'Philippines', phoneCode: '+63' },
  { id: 119, code: 'PL', name: 'Poland', phoneCode: '+48' },
  { id: 120, code: 'PT', name: 'Portugal', phoneCode: '+351' },
  { id: 121, code: 'QA', name: 'Qatar', phoneCode: '+974' },
  { id: 122, code: 'RO', name: 'Romania', phoneCode: '+40' },
  { id: 123, code: 'RU', name: 'Russia', phoneCode: '+7' },
  { id: 124, code: 'RW', name: 'Rwanda', phoneCode: '+250' },
  { id: 125, code: 'SA', name: 'Saudi Arabia', phoneCode: '+966' },
  { id: 126, code: 'SN', name: 'Senegal', phoneCode: '+221' },
  { id: 127, code: 'RS', name: 'Serbia', phoneCode: '+381' },
  { id: 128, code: 'SG', name: 'Singapore', phoneCode: '+65' },
  { id: 129, code: 'SK', name: 'Slovakia', phoneCode: '+421' },
  { id: 130, code: 'SI', name: 'Slovenia', phoneCode: '+386' },
  { id: 131, code: 'ZA', name: 'South Africa', phoneCode: '+27' },
  { id: 132, code: 'KR', name: 'South Korea', phoneCode: '+82' },
  { id: 133, code: 'ES', name: 'Spain', phoneCode: '+34' },
  { id: 134, code: 'LK', name: 'Sri Lanka', phoneCode: '+94' },
  { id: 135, code: 'SD', name: 'Sudan', phoneCode: '+249' },
  { id: 136, code: 'SE', name: 'Sweden', phoneCode: '+46' },
  { id: 137, code: 'CH', name: 'Switzerland', phoneCode: '+41' },
  { id: 138, code: 'SY', name: 'Syria', phoneCode: '+963' },
  { id: 139, code: 'TW', name: 'Taiwan', phoneCode: '+886' },
  { id: 140, code: 'TJ', name: 'Tajikistan', phoneCode: '+992' },
  { id: 141, code: 'TZ', name: 'Tanzania', phoneCode: '+255' },
  { id: 142, code: 'TH', name: 'Thailand', phoneCode: '+66' },
  { id: 143, code: 'TR', name: 'Turkey', phoneCode: '+90' },
  { id: 144, code: 'UG', name: 'Uganda', phoneCode: '+256' },
  { id: 145, code: 'UA', name: 'Ukraine', phoneCode: '+380' },
  { id: 146, code: 'AE', name: 'United Arab Emirates', phoneCode: '+971' },
  { id: 147, code: 'GB', name: 'United Kingdom', phoneCode: '+44' },
  { id: 148, code: 'US', name: 'United States', phoneCode: '+1' },
  { id: 149, code: 'UY', name: 'Uruguay', phoneCode: '+598' },
  { id: 150, code: 'UZ', name: 'Uzbekistan', phoneCode: '+998' },
  { id: 151, code: 'VE', name: 'Venezuela', phoneCode: '+58' },
  { id: 152, code: 'VN', name: 'Vietnam', phoneCode: '+84' },
  { id: 153, code: 'YE', name: 'Yemen', phoneCode: '+967' },
  { id: 154, code: 'ZM', name: 'Zambia', phoneCode: '+260' },
  { id: 155, code: 'ZW', name: 'Zimbabwe', phoneCode: '+263' }
];
